# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a40c5b1bec34531f314ac0cface151672675eaefb509f7678abe4dc8244a520e188fdff5e0f37005bf7e9e46a0224bcf34c15bd52f5bc3abf2a13be1750d94d

test:
  secret_key_base: 112d1e834090b322a4d245de14c7aa2cedfeff1ae79f1febab5b7e2a5a80af2ecc9bee7881e27c667816aefa0b9653684f4b89724049b51edd118680f372731f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
